name: Build Fonts
on:
  release:
    types: [published]

jobs:
  build:
    name: Build Fonts utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Build Environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build directory utils
        run: cargo build --release --manifest-path=utils/Cargo.toml
      - name: Build and package fonts
        env:
          ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: cargo run --release --manifest-path=utils/Cargo.toml --config ./fonts.json --base-path ./ --version ${{ github.ref_name }}